In [1]:
import pandas as pd
import matplotlib.pylab as plt

In [12]:
df=pd.read_csv("clean_df.csv",header=0)

In [13]:
df.describe()

,Unnamed: 0,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,...,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas,aspiration-std,aspiration-turbo
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,201.000000,...,205.000000,205.000000,205.000000,205.000000,201.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,102.000000,0.834146,122.000000,98.756585,0.836373,0.911588,0.898409,2555.565854,126.907317,3.329751,...,104.253659,5125.369458,25.219512,8.034347,13207.129353,9.949525,0.097561,0.902439,0.819512,0.180488
std,59.322565,1.245307,31.681008,6.021776,0.059285,0.029671,0.040862,520.680204,41.642693,0.273539,...,39.519219,476.979093,6.542142,1.849782,7947.066342,2.573104,0.297446,0.297446,0.385535,0.385535
min,0.000000,-2.000000,65.000000,86.600000,0.678039,0.834025,0.799331,1488.000000,61.000000,2.540000,...,48.000000,4150.000000,13.000000,4.351852,5118.000000,4.795918,0.000000,0.000000,0.000000,0.000000
25%,51.000000,0.000000,101.000000,94.500000,0.799135,0.886584,0.869565,2145.000000,97.000000,3.150000,...,70.000000,4800.000000,19.000000,6.911765,7775.000000,7.833333,0.000000,1.000000,1.000000,0.000000
50%,102.000000,1.000000,122.000000,97.000000,0.832292,0.905947,0.904682,2414.000000,120.000000,3.310000,...,95.000000,5200.000000,24.000000,7.833333,10295.000000,9.791667,0.000000,1.000000,1.000000,0.000000
75%,153.000000,2.000000,137.000000,102.400000,0.879865,0.925311,0.928094,2935.000000,141.000000,3.590000,...,116.000000,5500.000000,30.000000,9.400000,16500.000000,12.368421,0.000000,1.000000,1.000000,0.000000
max,204.000000,3.000000,256.000000,120.900000,1.000000,1.000000,1.000000,4066.000000,326.000000,3.940000,...,288.000000,6600.000000,49.000000,14.687500,45400.000000,18.076923,1.000000,1.000000,1.000000,1.000000

In [14]:
drive_wheels_counts=df["drive-wheels"].value_counts()

In [16]:
drive_wheels_counts.rename(columns={'drive-wheels':'value_counts' inplace=True})

SyntaxError: invalid syntax (<ipython-input-16-1f3d5f2bf86d>, line 1)